Always run pip with LANG=en_US.utf8
Found while running "pip3 download --no-binary :all: pyopenssl":

    UnicodeEncodeError: 'latin-1' codec can't encode characters in position 109-111: ordinal not in range(256)

And this would cause it to loop-fail. O__o

Another workaround might be to get it to omit installing the build deps.